### ISSUE TITLE
when opening the webui, the undersampling pre-search step is invalid

### ISSUE THREAD

**Issue by jiapeijia** [DataCanvasIO/HyperBoard#2]
<em>Please make sure that this is a bug. </em>

**System information**
- OS Platform: linux
- Python version:3.9
- HyperGBM version: 0.3 or 0.2.5.7
- hboard: 0.1.1

**Describe the current behavior**
if make_experiment() set down_sample_search=True and webui=True, hypernets will report the following warning, which results in invalid search steps.

10-26 11:32:31 W hypernets.e.__init__.py 1463 - Exception: Unseen Step class SpaceSearchWithDownSampleStep 
Traceback (most recent call last):
  File "/home/jiapj/miniconda3/envs/gbm_venv_3.9/lib/python3.9/site-packages/hypernets/experiment/_experiment.py", line 86, in run
    callback.experiment_start(self)
  File "/home/jiapj/miniconda3/envs/gbm_venv_3.9/lib/python3.9/site-packages/hboard/callbacks.py", line 125, in experiment_start
    super(WebVisExperimentCallback, self).experiment_start(exp)
  File "/home/jiapj/miniconda3/envs/gbm_venv_3.9/lib/python3.9/site-packages/hypernets/experiment/_callback.py", line 533, in experiment_start
    d = ExperimentExtractor(exp).extract()
  File "/home/jiapj/miniconda3/envs/gbm_venv_3.9/lib/python3.9/site-packages/hypernets/experiment/_extractor.py", line 670, in extract
    steps_meta = [self.extract_step(i, step) for i, step in enumerate(exp.steps)]
  File "/home/jiapj/miniconda3/envs/gbm_venv_3.9/lib/python3.9/site-packages/hypernets/experiment/_extractor.py", line 670, in <listcomp>
    steps_meta = [self.extract_step(i, step) for i, step in enumerate(exp.steps)]
  File "/home/jiapj/miniconda3/envs/gbm_venv_3.9/lib/python3.9/site-packages/hypernets/experiment/_extractor.py", line 633, in extract_step
    raise Exception(f"Unseen Step class {step_type} ")

**Comment by jiapeijia** [comment]
bug已定位
文件路径：hypernets\experiment\_extractor.py
在extractors中添加'SpaceSearchWithDownSampleStep': SpaceSearchStepExtractor。
如下所示：
extractors = {
        StepType.DataAdapting: DataAdaptionStepExtractor,
        StepType.DataCleaning: DataCleanStepExtractor,
        StepType.FeatureGeneration: FeatureGenerationStepExtractor,
        StepType.DriftDetection: DriftStepExtractor,
        StepType.FeatureSelection: FeatureSelectionStepExtractor,
        StepType.CollinearityDetection: MultiLinearityStepExtractor,
        StepType.PseudoLabeling: PseudoStepExtractor,
        StepType.DaskPseudoLabelStep: PseudoStepExtractor,
        StepType.PermutationImportanceSelection: PermutationImportanceStepExtractor,
        StepType.SpaceSearch: SpaceSearchStepExtractor,
        'SpaceSearchWithDownSampleStep': SpaceSearchStepExtractor,
        StepType.FinalTrain: FinalTrainStepExtractor,
        StepType.Ensemble: EnsembleStepExtractor,
        StepType.DaskEnsembleStep: EnsembleStepExtractor
    }
